# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [ ]:
s = "hi there sam!"
s.split()

['hi', 'there', 'sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [ ]:

str.format("the diameter of the {plant},is{diameter}".format(plant = "earth",diameter ="12742"))

'the diameter of the earth,is12742'

## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
list1 = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}
list1.remove('hello')

SyntaxError: ignored

# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [ ]:
import numpy as np
b = np.zeros( (10),dtype=float)
print(b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
import numpy as np
b = np.zeros( (5),dtype=float)
print(b)

[0. 0. 0. 0. 0.]


## 5. Create an array of all the even integers from 20 to 35

In [ ]:
import array
import numpy as np
array=np.arange(20,36,2)
print("array of the even")
print(array)

array of the even
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
import numpy as np
x = np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
array1 = [1, 2, 3]
array2= [4, 5, 6]
for item in array2:
  array1.append(item)
  print (array1)

[1, 2, 3, 4]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [ ]:
import pandas as pd
data = [10,20,30]
df = pd.DataFrame(data,columns=['numbers'])
df


numbers
0       10
1       20
2       30

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
import pandas as pd 
from datetime import datetime
import numpy as np
range_date= pd.date_range(start ="1/1/2023",end = "10/2/2023",freq = 'min')
print(range_date)

DatetimeIndex(['2023-01-01 00:00:00', '2023-01-01 00:01:00',
               '2023-01-01 00:02:00', '2023-01-01 00:03:00',
               '2023-01-01 00:04:00', '2023-01-01 00:05:00',
               '2023-01-01 00:06:00', '2023-01-01 00:07:00',
               '2023-01-01 00:08:00', '2023-01-01 00:09:00',
               ...
               '2023-10-01 23:51:00', '2023-10-01 23:52:00',
               '2023-10-01 23:53:00', '2023-10-01 23:54:00',
               '2023-10-01 23:55:00', '2023-10-01 23:56:00',
               '2023-10-01 23:57:00', '2023-10-01 23:58:00',
               '2023-10-01 23:59:00', '2023-10-02 00:00:00'],
              dtype='datetime64[ns]', length=394561, freq='T')


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
import pandas as pd
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df = pd.DataFrame(lists, columns =['s.no','tag','name'],dtype = float)
print(df)

   s.no  tag  name
0   1.0  aaa  22.0
1   2.0  bbb  25.0
2   3.0  ccc  24.0


/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3326: FutureWarning: Could not cast to float64, falling back to object. This behavior is deprecated. In a future version, when a dtype is passed to 'DataFrame', either all columns will be cast to that dtype, or a TypeError will be raised
  exec(code_obj, self.user_global_ns, self.user_ns)
